name: Build FBE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: "Build Win32"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build Solution
      run: msbuild FictionBookEditorPortable.sln /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FBE_Portable_Win32
        path: src\Package\*
        if-no-files-found: error

  release:
    needs: [build]
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    name: "Release"
    permissions:
      contents: write

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: FBE_Portable_Win32

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.6.1
      with:
        tag_name: FBE-Portable-2.8.0
        body: "Тест 2.8.0"
        draft: false
        prerelease: false
        overwrite_files: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}